### PR TITLE
fix: needs python to run in K8; backend agnostic rqmts install

### LINKED ISSUE #430: fix: python-* tests do not work with K8 backend
```
apps % kubectl logs l1-python-language-doc-chunk-ansu-c2c48e9a-workerpool-2llhs -n python-language-doc-chunk
Defaulted container "main" out of: main, workdir-code (init), watcher (init)
Error: open /var/folders/bm/g5v5z56x2wj0pz448v4t91sw0000gn/T/requirements.txt1913859458: no such file or directory
Lunchpail worker starting up
Traceback (most recent call last):
  File "/workdir/./main.py", line 15, in <module>
    import pyarrow.parquet as pq
ModuleNotFoundError: No module named 'pyarrow'
Internal Error running the handler: exit status 1
Worker error with exit code 1 while processing task.1.txt
exit status 1%                  
```

### PR DESCRIPTION
**Pull request by aavarghese**
Fixes #430 

Tests that run on target=kubernetes using Datasets restricted to `local` target until writeBlobsToWorkdir is implemented for K8. Some other tests also running on local only due to other known errors like large model, etc

### CODE REVIEW

File: cmd/subcommands/needs/python.go [hunk 1]
```diff
@@ -11,24 +11,24 @@ import (
 )
 
 func Python() *cobra.Command {
-	var requirementsPath string
+	var requirements string
 	cmd := &cobra.Command{
-		Use:   "python <version> [-r /path/to/requirements.txt]",
+		Use:   "python <version> [-r encodedRequirements]",
```
Comment (starpit) [inline cmd/subcommands/needs/python.go:16]: encodedRequirements -> base64EncodedRequirements?

**Review by starpit — DISMISSED** [review]
